### ISSUE TITLE
Script breaks youtube live chat for Chrome Version 87.0.4280.88 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by SeeDRankA** [zerodytrash/YouTube-Livechat-Channel-Resolver#2]
Hello your script now breaks the livechat for livestreams in Windows Chrome version: [https://cdn.discordapp.com/attachments/108022648595820544/784284696595005491/unknown.png](url)

Screenshot:
[https://cdn.discordapp.com/attachments/108022648595820544/784284646900891648/unknown.png](url)  copy and paste links if they dont work.

**Comment by zerodytrash** [comment]
hi,
YouTube has released an update which unfortunately caused problems with the script. 
This should be fixed now. Please update to the latest version.

**Comment by SeeDRankA** [comment]
Thanks! I recommended this to all the moderators i work with. Go To Channel may be even better now since it's now low key, and the people that need it as tool its still here because of your efforts. Thank you again!
![image](https://user-images.githubusercontent.com/75465630/101268137-83d4a180-3725-11eb-9437-69f92d8b476f.png)
