### ISSUE TITLE
Not working with Greasemonkey on Firefox

### ISSUE THREAD

**Issue by Juxxtapoz** [zerodytrash/YouTube-Livechat-Channel-Resolver#4]
Hey,

Recently it seems like the script is no longer working with Greasemonkey on Firefox. Chrome still works just fine. Any ideas?

**Comment by zerodytrash** [comment]
Hi,

there was a small error in the version. Update to the latest version (0.8), then it should work.

**Comment by Juxxtapoz** [comment]
> Hi,
> 
> there was a small error in the version. Update to the latest version (0.8), then it should work.

That seems to have fixed it. Thanks for your help.
